title: SAIKAT SHARMA
logo: /assets/img/logo.png
description: Fortunes favor the braves. No one knows what the future holds that's why its potential is infinity so keep trying hard - Steins;Gate
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
author: Saikat Sharma
